export const env = {
  GEOCODE_EARTH_TOKEN: import.meta.env.VITE_PUBLIC_GEOCODE_EARTH_TOKEN,
  ROUTING_PROVIDER: import.meta.env.VITE_PUBLIC_ROUTING_PROVIDER,
  ROUTING_API_KEY: import.meta.env.VITE_PUBLIC_ROUTING_API_KEY,
  ROUTING_URL: import.meta.env.VITE_PUBLIC_ROUTING_URL,
  OSRM_DRIVING_URL: import.meta.env.VITE_PUBLIC_OSRM_DRIVING_URL,
  OSRM_WALKING_URL: import.meta.env.VITE_PUBLIC_OSRM_WALKING_URL,
  OSRM_CYCLING_URL: import.meta.env.VITE_PUBLIC_OSRM_CYCLING_URL,
};
