export const env = {
  MAPBOX_TOKEN: import.meta.env.VITE_PUBLIC_MAPBOX_TOKEN,
  GEOCODE_EARTH_TOKEN: import.meta.env.VITE_PUBLIC_GEOCODE_EARTH_TOKEN,
  DROPBOX_APP_KEY: import.meta.env.VITE_PUBLIC_DROPBOX_APP_KEY,
};
