services:
  db:
    image: postgres:16.1
    restart: always
    env_file:
      - .env.local
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  web: &web
    build:
      dockerfile: dev.Dockerfile
    env_file:
      - .env.local
    volumes:
      - .:/app
    user: node
    command: yarn dev
    ports:
      - 3000:3000
    depends_on:
      - db
  prisma:
    <<: *web
    command: >
      /bin/sh -c '
        yarn prisma migrate dev &&
        yarn studio
      '
    ports:
      - 5555:5555

volumes:
  db:
    driver: local
