version: "3"
services:
  db:
    image: postgres:16.1
    container_name: placemark-db
    restart: always
    env_file:
      - .env.local
    volumes:
      - db:/var/lib/postgresql/data
    # ports:
    #   - 5432:5432
    networks:
      - placemark
  web: &web
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: placemark-web
    restart: unless-stopped
    env_file:
      - .env.local
    volumes:
      - .:/app
    user: node
    command: /bin/sh -c 'blitz prisma migrate deploy  && blitz prisma generate && pnpm run dev'
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - placemark
  prisma:
    <<: *web
    container_name: placemark-studio
    restart: unless-stopped
    command: >
      /bin/sh -c '
        pnpm run prisma migrate dev &&
        pnpm run studio
      '
    ports:
      - 5555:5555
    depends_on:
      - db
    networks:
      - placemark

volumes:
  db:
    driver: local

networks:
  placemark:
    driver: bridge
