name = "data-library"
main = "src/index.ts"
compatibility_date = "2022-09-21"
routes = [
  { pattern = "data-library.placemark.io", custom_domain = true, zone_name = "placemark.io" }
]

[[r2_buckets]]
binding = 'APP_BUILD' # <~ valid JavaScript variable name
bucket_name = 'placemark-data-library'
preview_bucket_name = 'placemark-data-library-dev'
